version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        links:
            - fpm
        volumes:
            - ./code:/var/www/laravel
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        working_dir:
            /var/www/laravel
        networks:
          - app-network

    fpm:
        build: ./docker/php-fpm
        links:
            - db
        volumes:
            - ./code:/var/www/laravel
        working_dir:
            /var/www/laravel
        networks:
          - app-network

    db:
        build: ./docker/mysql
        volumes:
            - data:/var/lib/mysql
        container_name: nemo_db
        environment:
            MYSQL_ROOT_PASSWORD: rootp@ss
            MYSQL_DATABASE: nemo
        networks:
          - app-network

volumes:
    data:

networks:
  app-network:
    driver: bridge
