version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "5001:80"
        links:
            - fpm
        volumes:
            - ./code:/var/www/laravel
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        working_dir:
            /var/www/laravel
    fpm:
        build: ./docker/php-fpm
        links:
            - db
        volumes:
            - ./code:/var/www/laravel
        working_dir:
            /var/www/laravel

    db:
        build: ./docker/mysql
        ports:
            - "3361:3360"
        volumes:
            - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootp@ss
            MYSQL_DATABASE: nemo

volumes:
    data:
